[toolchain]
channel = "nightly-2026-04-06"

targets = [
    # Windows
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    # Linux
    #"aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    # macOS
    "aarch64-apple-darwin",
]