name: kyber
description: Package that provides Kyber specific utilities and clients.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dev_dependencies:
  very_good_analysis: ^10.0.0

dependencies:
  dio: ^5.4.3+1
  grpc: ^5.0.0
  protobuf: ^6.0.0
  uuid: ^4.4.2
  kyber_collection:
    path: ../kyber_collection
