name: nexus_bridge
description: Plugin to interact with Nexusmods
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^10.0.0
  retrofit_generator:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: generator
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: retrofit

dependencies:
  csv: ^6.0.0
  dio: ^5.4.0
  html: ^0.15.4
  logger: any
  json_annotation: ^4.8.1
  rxdart: ^0.28.0
  protobuf: ^6.0.0
